config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to:'pages#top'
  resources :pages

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def top
    end
    
    def show
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PFHp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/*******.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
      <ul class="nav-list">
        <li class="nav-list-item">
          <%= link_to root_path do %>
          HOME
          <% end %>
        </li>
        <li class="nav-list-item">
          <%= link_to pages_path do %>
          Profire
          <% end %>
        </li>
        <li class="nav-list-item">
          <a href="#">Blog</a>
        </li>
      </ul>
    </nav>  
    </header>

    <!-- navigation -->
    
    <%= yield %>
    
    <footer>
      <div class= "container">
        <div class = "row">
          <div class="col-xs-12 col-sm-4">
				<h4>About me!</h4>
				<hr>
				<div style="clear:both"></div>
				<p>プログラミングを勉強中の23歳。
				</br>日頃は営業として働いてます！</p>
				<a href="#" style="color:#337ab7;">» プロフィール詳細はこちら</a><br>
				<a href="#" style="color:#337ab7;">» お問い合わせはこちら</a><br>
				<a href="#" style="color:#337ab7;">» サイトマップはこちら</a>
			</div>
			<!--
			<div class="col-xs-12 col-sm-4">
			  
				<h4>SNS</h4>
				<hr>
				<div style="clear:both"></div>
				<ul class="list-unstyled">
					<li><a href="#" target="new" rel="nofollow">休活BLOG</a></li>
					<li><a href="#" target="new" rel="">Manablog Copy｜当サイトのWordPressテーマ</a></li>
					<li><a href="#" target="new" rel="nofollow">nomad links</a></li>
					<li><a href="#" target="new" rel="nofollow">Minimal - ミニマリスト向けのWordPressテーマ</a></li>
					<li><a href="#" target="new" rel="nofollow">Book That Changed Your Life</a></li>
					<li><a href="#" target="new" rel="nofollow">あなたの人生を変えた本</a></li>
					
				</ul>
			</div>
			--
        </div>
      </div>
      <div class="container-fluid credit">
		<div class="row">
			<p class="col-xs-12 text-center">Copyright - <a href="#">NUNOO</a>, 2021 All Rights Reserved.</p>
		</div>
	</div>
    </footer>
  </body>
</html>

app/views/pages/show.html.erb
<main>
 プログラミング勉強中の社会人！！!
 24歳
</main>

app/views/pages/top.html.erb
<div class="main-visual">
    <div class="main-visual-content">
      <h1 class="main-visual-text">
          My <span style="font-family:futura-lt-w01-light,sans-serif">Portforio</span> page.
      </h1>
                
    </div>
</div>
        
<!--ポートフォリオの部分-->
<main>
      <section class="blog">
        <h2 class="blog-heading">Recent Blogs</h2>

        <div class="blog-box">
          <div class="blog-item">
            <%= image_tag('stareco.jpg', class: 'blog-image') %>
            <section class="blog-text">
              <div class="blog-text-heading">
                <a href="http://54.238.90.188/">
                  <h3>【スタレコ】</h3><br />
                    <p>営業の方々向けの顧客管理ツールを<br />
                イメージして作成しました。<br/>
                ※初めてのポートフォリオなのでクオリティはご愛嬌</p>
                </a>
              </div>
              <p class="blog-date">2022/02/20</p>
              <span class="category">ポートフォリオ</span>
            </section>
          </div>
        </div>      </section>
      <div class="sidebar"></div>
    </main>